version: "3.3"
services:
  learn-js:
    image: learn-js:1.0
    container_name: learn-js
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/home/app
      # - ./app/public:/home/app/public
      # - ./app/src:/home/app/src
    ports:
      - 7000:5500
    tty: true
    stdin_open: true
