version: '3.3'
services:
  front:
    image: ${PROJ_NAME}:latest
    container_name: ${PROJ_NAME}
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front/app:/home/app
      - front-volume:/home/app/node_modules
    ports:
      - ${DEV_PORT}:3000
      - ${PROD_PORT}:5000
    tty: true
volumes:
  front-volume:
    name: ${PROJ_NAME}-volume
    driver: local
