version: '3.3'
services:
  front:
    image: basement-js:latest
    container_name: basement-js
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front/app:/home/app
      - /home/app/node_modules
    ports:
      - ${DEV_PORT}:3000
      - ${PROD_PORT}:5000
    tty: true
